/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

import moviezoom.MovieInfo;
import javax.swing.*;
/**
 *
 * @author Ragul S
 */
public class Catalog extends javax.swing.JFrame {

    JFrame j = new JFrame();
    /**
     * Creates new form Catalog
     */
    public Catalog() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        actortxt = new javax.swing.JTextField();
        dirtxt = new javax.swing.JTextField();
        yeartxt = new javax.swing.JTextField();
        ratingtxt = new javax.swing.JTextField();
        genretxt = new javax.swing.JTextField();
        tapetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        formattxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Addmovie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD MOVIE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 108, 63, 34));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Actor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 160, 63, 34));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Director");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 212, 63, 34));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Year");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 264, 63, 34));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Rating");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 316, 63, 34));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Genre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 368, 63, 34));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tape");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 420, 63, 34));
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 115, 242, -1));
        getContentPane().add(actortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 167, 242, -1));
        getContentPane().add(dirtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 219, 242, -1));
        getContentPane().add(yeartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 264, 242, -1));
        getContentPane().add(ratingtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 328, 242, -1));
        getContentPane().add(genretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 380, 242, -1));
        getContentPane().add(tapetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 427, 242, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Format");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 472, 63, 34));
        getContentPane().add(formattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 479, 242, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("MovieZoom");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 20, 236, 56));

        Addmovie.setBackground(new java.awt.Color(102, 255, 102));
        Addmovie.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Addmovie.setText("Add");
        Addmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddmovieActionPerformed(evt);
            }
        });
        getContentPane().add(Addmovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 541, 75, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Validate(){
        //JFrame addMsg = new JFrame();
        //addMsg.setVisible(false);
        try{
            String name = nametxt.getText();
            String actor = actortxt.getText();
            String director = dirtxt.getText();
            String year = yeartxt.getText();
            String rating = ratingtxt.getText();
            String genre = genretxt.getText();
            String tape = tapetxt.getText();
            String format = formattxt.getText();
            
            if(name.equals("") || actor.equals("") || director.equals("") || year.equals("") || rating.equals("") || genre.equals("") || tape.equals("") || format.equals(""))
                throw new NullPointerException();
            
            MovieInfo addinfo = new MovieInfo();
            
            addinfo.setActor(actor);
            addinfo.setTitle(name);
            addinfo.setDirector(director);
            addinfo.setYear(year);
            addinfo.setRating(rating);
            addinfo.setTape(tape);
            addinfo.setGenre(genre);
            addinfo.setFormat(format);
            
            
            MovieInfo.Add(addinfo);
            
            //addMsg.setVisible(true);
            JOptionPane.showMessageDialog(null,"Movie Added Successfully");
            setVisible(false);
        }
        catch(NullPointerException e){
            //addMsg.setVisible(true);
            JOptionPane.showMessageDialog(null,"Please Enter all fields");
        }
    }
    
    private void AddmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddmovieActionPerformed
        Validate();
    }//GEN-LAST:event_AddmovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addmovie;
    private javax.swing.JTextField actortxt;
    private javax.swing.JTextField dirtxt;
    private javax.swing.JTextField formattxt;
    private javax.swing.JTextField genretxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField ratingtxt;
    private javax.swing.JTextField tapetxt;
    private javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
